export const weatherIcons = {
  0: <img src="/assets/0.webp" />,                 // Clear sky
  1: <img src="/assets/icon-overcast.webp" />,                   // Mainly clear
  2: <img src="/assets/icon-overcast.webp" />,                   // Partly cloudy
  3: <img src="/assets/icon-overcast.webp" />,                   // Overcast
  45: <img src="/assets/icon-fog.webp" />,                  // Fog
  48: <img src="/assets/icon-fog.webp" />,                  // Rime fog
  51: <img src="/assets/icon-drizzle.webp" />,                 // Light drizzle
  53: <img src="/assets/icon-drizzle.webp" />,                 // Moderate drizzle
  55: <img src="/assets/icon-drizzle.webp" />,                 // Dense drizzle
  56: <img src="/assets/icon-snow.webp" />,                // Light freezing drizzle
  57: <img src="/assets/icon-snow.webp" />,                // Dense freezing drizzle
  61: <img src="/assets/icon-rain.webp" />,                   // Slight rain
  63: <img src="/assets/icon-rain.webp" />,                   // Moderate rain
  65: <img src="/assets/icon-rain.webp" />,                   // Heavy rain
  66: <img src="/assets/icon-snow.webp" />,                // Light freezing rain
  67: <img src="/assets/icon-snow.webp" />,                // Heavy freezing rain
  71: <img src="/assets/icon-snow.webp" />,                  // Slight snow
  73: <img src="/assets/icon-snow.webp" />,                  // Moderate snow
  75: <img src="/assets/icon-snow.webp" />,                  // Heavy snow
  77: <img src="/assets/icon-snow.webp" />,          // Snow grains
  80: <img src="/assets/icon-rain.webp" />,                   // Slight rain shower
  81: <img src="/assets/icon-rain.webp" />,                   // Moderate rain shower
  82: <img src="/assets/icon-rain.webp" />,                   // Violent rain shower
  85: <img src="/assets/icon-snow.webp" />,          // Slight snow shower
  86: <img src="/assets/icon-snow.webp" />,          // Heavy snow shower
  95: <img src="/assets/icon-storm.webp" />,            // Thunderstorm slight/moderate
  96: <img src="/assets/icon-storm.webp" />,            // Thunderstorm + slight hail
  99: <img src="/assets/icon-storm.webp" />,            // Thunderstorm + heavy hail
};
